apiVersion: v1
kind: Service
metadata:
  name: demo-cicd-service
spec:
  type: NodePort
  selector:
    app: demo-cicd-app
  ports:
    - port: 80          # Service port (what clients see)
      targetPort: 8080  # Container port (Spring Boot)
      nodePort: 30080   # NodePort (fixed, optional; 30000â€“32767)
